[package]
name = "rust_playground"
version = "0.1.0"
edition = "2021"
authors = ["spedon <realsped0n@outlook.com>"]
description = "A playground for learning Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
